// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK5i8jhzTws3TrdwMTdxdW2mK_M6UnbGg',
    appId: '1:1864554135:web:50c0f55ecc75fdb3907bd2',
    messagingSenderId: '1864554135',
    projectId: 'flutter-firebase-a7188',
    authDomain: 'flutter-firebase-a7188.firebaseapp.com',
    storageBucket: 'flutter-firebase-a7188.firebasestorage.app',
    measurementId: 'G-VFQ917CVSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwzzX1e8g-qjRjMUfaNSWUkjb51t_lRtk',
    appId: '1:1864554135:android:0436f51c9f6f744d907bd2',
    messagingSenderId: '1864554135',
    projectId: 'flutter-firebase-a7188',
    storageBucket: 'flutter-firebase-a7188.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFi5PA85o8WLACyc9VMXrbHy0MBGLkfjM',
    appId: '1:1864554135:ios:0a8ea218c4482424907bd2',
    messagingSenderId: '1864554135',
    projectId: 'flutter-firebase-a7188',
    storageBucket: 'flutter-firebase-a7188.firebasestorage.app',
    iosBundleId: 'com.example.healthcare',
  );
}
